### ISSUE TITLE
502 bad gateaway... Define path, user/group and port?

### ISSUE THREAD

**Issue by cellulosa** [hellstad/meteor-please#6]
hi @hellstad, great script. thanks. Issue is, I can't run the app as it always errors 502. Here's my nginx config for the deployed app:

```
location / {
    proxy_pass http://127.0.0.1:3000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
}
```

As I'm running multiple websites on the same machine, it may be possible it is a configuration issue. Would it be possible to define:
1) deploy path
2) user/group
3) node port
in `mplz.json`?

**Comment by kevincharm** [comment]
Hi @cellulosa, does your machine have SELinux enabled? Nginx might be getting denied. (Check the last part of this [gist](https://gist.github.com/hellstad/587c65a210df74b182a6))

Right now all the deploy path/user/port are predefined. I'm working on a totally new version at the moment which will be more flexible. So unfortunately I will not be working on the current version. PRs are welcome though if you would like to add those features :)

**Comment by cellulosa** [comment]
hi @hellstad thank you for your reply. I'm really glad to know you're working on a newer version of `meteor-please` and I'm looking forward to it.

Anyway no, I do not have SELinux enabled. This is the output of `systemctl status app.service`:

```
app.service - app nodejs daemon
   Loaded: loaded (/etc/systemd/system/app.service; enabled)
   Active: failed (Result: start-limit) since Mon 2015-11-16 11:33:31 EST; 14min ago
  Process: 29092 ExecStart=/usr/local/bin/node /var/www/app/bundle/main.js (code=exited, status=1/FAILURE)
 Main PID: 29092 (code=exited, status=1/FAILURE)
   CGroup: /system.slice/app.service

app[29092]: at Module._compile (module.js:460:26)
app[29092]: at Object.Module._extensions..js (module.js:478:10)
systemd[1]: app.service: main process exited, code=exited, status=1/FAILURE
systemd[1]: Unit app.service entered failed state.
systemd[1]: app.service holdoff time over, scheduling restart.
systemd[1]: Stopping app nodejs daemon...
systemd[1]: Starting app nodejs daemon...
systemd[1]: app.service start request repeated too quickly, refusing to start.
systemd[1]: Failed to start app nodejs daemon.
systemd[1]: Unit app.service entered failed state.
```

And if I try to run the app manually (`node main.js`) it returns:

```
/var/www/app/bundle/programs/server/node_modules/fibers/future.js:245
                        throw(ex);
                              ^
Error: MONGO_URL must be set in environment
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:36:1)
    at Object.defaultRemoteCollectionDriver (packages/underscore/packages/underscore.js:779:1)
    at new Mongo.Collection (packages/mongo/collection.js:102:1)
    at AccountsServer.AccountsCommon (accounts_common.js:23:18)
    at new AccountsServer (accounts_server.js:16:5)
    at Package (globals_server.js:5:12)
    at /var/www/app/bundle/programs/server/packages/accounts-base.js:1814:4
    at /var/www/app/bundle/programs/server/packages/accounts-base.js:1825:3
    at /var/www/app/bundle/programs/server/boot.js:242:10
    at Array.forEach (native)
```

But I guess that's because the environment variables are via systemd

**Comment by kevincharm** [comment]
You'll be able to get full error logs from using `journalctl -u app` instead of `systemctl status` (and scrolling to the bottom of the file). It looks like maybe some npm module didn't compile properly, but need to see the full error message from before this line 
`app[29092]: at Module._compile (module.js:460:26)`

**Comment by cellulosa** [comment]
it says

```
systemd[1]: Starting app nodejs daemon...
systemd[1]: Started app nodejs daemon.
app[10566]: /var/www/app/bundle/programs/server/boot.js:283
app[10566]: }).run();
app[10566]: ^
app[10566]: Error: $ROOT_URL, if specified, must be an URL
app[10566]: at Error (<anonymous>)
app[10566]: at Meteor.absoluteUrl.options (packages/meteor/url_server.js:8:1)
app[10566]: at /var/www/app/bundle/programs/server/packages/meteor.js:1132:4
app[10566]: at /var/www/app/bundle/programs/server/packages/meteor.js:1274:3
app[10566]: at /var/www/app/bundle/programs/server/boot.js:242:10
app[10566]: at Array.forEach (native)
app[10566]: at Function._.each._.forEach (/var/www/app/bundle/programs/server/nod
app[10566]: at /var/www/app/bundle/programs/server/boot.js:137:5
systemd[1]: app.service: main process exited, code=exited, status=8/n/a
systemd[1]: Unit app.service entered failed state.
systemd[1]: app.service holdoff time over, scheduling restart.
systemd[1]: Stopping app nodejs daemon...
systemd[1]: Starting app nodejs daemon...
systemd[1]: Started app nodejs daemon.
```

That's `/etc/systemd/system/app.service` as generated by `meteor-please`

```
[Unit]
Description=app nodejs daemon
After=network.target remote-fs.target

[Service]
User=meteor-please
ExecStart=/usr/local/bin/node /var/www/app/bundle/main.js
Restart=always
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=app
Environment=ROOT_URL=127.0.0.1
Environment=PORT=3000
Environment=NODE_ENV=production
Environment=MONGO_URL=mongodb://127.0.0.1:27017/app
Environment=METEOR_SETTINGS=

[Install]
WantedBy=multi-user.target
```

**Comment by kevincharm** [comment]
Hmm, from that log it seems it has a problem with the ROOT_URL. Could you try to edit the `env.ROOT_URL` line in your `mplz.json` to the domain you're using, like this:

```
  "env": {
    "ROOT_URL": "http://linkstash.xyz"
  }
```

Then run `mplz setup && mplz deploy` again, and see if it helps? I do admit the app generates a less than perfect `mplz.json` at the moment and I have not supplied any documentation.

Here is a sample of one of my configuration files to compare against yours (use node 0.10.36 for Meteor 1.1.x and lower)

```
{
  "appName": "linkstash",
  "servers": [
    {
      "host": "198.199.254.255",
      "username": "root",
      "pem": "~/dev/some-pem"
    }
  ],
  "setupMongo": true,
  "setupNode": true,
  "nodeVersion": "0.10.40",
  "setupNginx": true,
  "sslcert": "",
  "sslkey": "",
  "verbosity": true,
  "appSiteUrl": "linkstash.xyz",
  "app": ".",
  "env": {
    "ROOT_URL": "http://linkstash.xyz"
  }
}
```

**Comment by cellulosa** [comment]
O see. Alright, that worked. Thank you!

Yes I think it would be essential to provide some documentation - even just this sample you supplied.
